// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) connection -- required for CLI/migration
    // commands, distinct from the pooled DATABASE_URL the app runtime
    // uses via src/lib/db.ts. Prisma 7 removed the old directUrl config
    // field, so this is the only place the direct connection is wired.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
