// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// The default `import "dotenv/config"` only auto-loads `.env`, never
// `.env.local` -- which is where `vercel env pull` writes the real Neon
// credentials. Loading both explicitly, `.env.local` first: per dotenv's
// own `path`-array semantics, the first file's value for a given key wins
// over later files, and neither ever overrides a value already present in
// process.env (no `override` flag set) -- so a DATABASE_URL_UNPOOLED
// already provided by Vercel/CI/the shell is left untouched, `.env.local`
// is preferred over `.env` for anything not already set, and `quiet`
// suppresses dotenv's own runtime log line.
dotenv.config({ path: [".env.local", ".env"], quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) connection -- required for CLI/migration
    // commands, distinct from the pooled DATABASE_URL the app runtime
    // uses via src/lib/db.ts. Prisma 7 removed the old directUrl config
    // field, so this is the only place the direct connection is wired.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
